apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: myapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=db-service;Port=5432;Database=myapp;Username=postgres;Password=Test123"
        - name: ASPNETCORE_ENVIRONMENT
          value: Development

