version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      db:
        condition: service_healthy  
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myapp;Username=postgres;Password=Test123
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork

  db:
    image: postgres:15 
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: Test123
      POSTGRES_DB: myapp
    ports:
      - "5434:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

networks:
  mynetwork:
    driver: bridge 

volumes:
  postgres-data:
    driver: local
