version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - db 
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myapp;Username=postgres;Password=Test123
    networks:
      - mynetwork

  db:
    image: postgres:15 
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: Test123
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge 

volumes:
  postgres-data:
    driver: local
