name: Docker Image Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Pobranie kodu z repozytorium
    - name: Checkout repository
      uses: actions/checkout@v3

    # Budowanie obrazu Dockerowego
    - name: Build Docker Image
      run: docker-compose -f docker-compose.yml build app
